name: DreamOC
favicon: null
layout_spectrum: 0.61765
typography_spectrum: 0.13713
title: Stop and Wonder
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#c6c6c4'
    - '#221a22'
    - '#3a5c4e'
    - '#8a8889'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
